f=open('深度学习及智能驾驶模型实操教程_v2.1.md','rb')
c=f.read()
f.close()
t=c.decode('utf-8')
t=t.replace('为什么必须预测"。\r\n\r\n# 3.2.3','为什么必须预测"。\r\n\r\n**对应实操**：4.2节行为克隆展示最简单的感知-动作映射（无预测）。\r\n\r\n# 3.2.3',1)
f=open('深度学习及智能驾驶模型实操教程_v2.1.md','wb')
f.write(t.encode('utf-8'))
f.close()
print('现在有',t.count('**对应实操**'),'个实操引用')
